name: Compile LaTeX

on:
  push:
    paths:
      - '**.tex'   # Run only when .tex files change
  pull_request:
    paths:
      - '**.tex'

jobs:
  build-latex:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up LaTeX environment
      - name: Install LaTeX
        run: sudo apt-get update && sudo apt-get install -y texlive-full

      # 3. Compile all modified .tex files
      - name: Compile modified .tex files
        run: |
          for file in $(git diff --name-only HEAD~1 HEAD | grep '\.tex$'); do
            echo "Compiling $file..."
            latexmk -pdf -interaction=nonstopmode -halt-on-error "$file"
          done

      # 4. (Optional) Upload PDFs as artifacts
      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdfs
          path: |
            **/*.pdf

      # 5. (Optional) Commit PDFs back to repo
      - name: Commit compiled PDFs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add **/*.pdf
          git commit -m "Auto-compile PDFs [skip ci]" || echo "No changes"
          git push





