name: Compile and Commit LaTeX PDFs

on:
  push:
    paths:
      - '**.tex'
  pull_request:
    paths:
      - '**.tex'

jobs:
  compile-tex:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository with full history
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 2  # Fetch last two commits to allow HEAD^ diff

    - name: Set up Git user
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Install TeX Live
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full

    - name: Compile changed .tex files
      run: |
        tex_files=$(git diff --name-only HEAD^ HEAD | grep '\.tex$' || true)

        if [ -z "$tex_files" ]; then
          echo "No .tex files changed."
          exit 0
        fi

        updated_pdfs=0

        for file in $tex_files; do
          dir=$(dirname "$file")
          base=$(basename "$file" .tex)

          echo "Compiling $file"
          latexmk -pdf -output-directory="$dir" "$file"

          if [ -f "$dir/$base.pdf" ]; then
            git add "$dir/$base.pdf"
            updated_pdfs=1
          fi

          latexmk -c -output-directory="$dir" # optional cleanup
        done

        if [ "$updated_pdfs" -eq 1 ]; then
          git commit -m "Auto-compiled PDF(s) from changed .tex"
          git push
        else
          echo "No PDFs generated to commit."
        fi



